/**
 * M9 deploy-target manager (PLAN-M9.md + PLAN.md §6.1 "Ship").
 *
 * Deploy-target profiles describe where a built app lands (v1: a docker-ssh
 * host behind an existing reverse proxy). The manager owns:
 *
 *   - CRUD with validation: kind is ALWAYS docker-ssh in v1, host must be a
 *     non-empty host string, port is an integer 1-65535 defaulting to 22.
 *     env_extra is a column reserved for later milestones — it is NOT part
 *     of the API and secret VALUES are never accepted anywhere.
 *   - package(profileId, {projectDir, outDir}): produces the
 *     CONTAINER-READY bundle folder locally: Dockerfile + .dockerignore +
 *     README + a generated build script the CALLER runs on the build host
 *     (esbuild etc. — the core never invokes esbuild at runtime). The
 *     returned PackageResult carries the written file paths and the
 *     Dockerfile text.
 *
 * Live push/deploy to the org infrastructure stays environment-gated
 * (documented in the README + PLAN-M9 "out of scope") — this milestone
 * ships the loop that feeds it: profile, validation and the bundle.
 *
 * Audit rows are `deploy-profile.*` with ids/names/counts only — never
 * connection credentials (this manager stores no keys; env values never
 * reach audit).
 */
import { chmodSync, existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { isAbsolute, join } from 'node:path';
import { randomUUID } from 'node:crypto';
import type { DeployProfile, DeployProfileInput, PackageResult } from '@partner/shared';
import type { DeployProfileRow, DeployProfileStore } from '../stores/types.js';
import type { AuditService } from '../services/redaction.js';
import { playbookError } from './errors.js';

export interface DeployManagerOptions {
  store: DeployProfileStore;
  audit: AuditService;
  /** Injectable clock (epoch ms). */
  now?: () => number;
}

export interface DeployPackageInput {
  /** Broker project root whose app is being shipped (absolute dir). */
  projectDir: string;
  /** Absolute folder the bundle is written into (created recursively). */
  outDir: string;
}

export interface DeployManager {
  list(): DeployProfile[];
  create(input: DeployProfileInput): DeployProfile;
  /** Unknown id -> not_found. */
  remove(id: string): void;
  /**
   * Validate the profile, then write the container-ready bundle into
   * outDir (mkdir -p). Returns written file paths + the Dockerfile text.
   */
  package(profileId: string, input: DeployPackageInput): PackageResult;
}

function rowToProfile(row: DeployProfileRow): DeployProfile {
  return {
    id: row.id,
    name: row.name,
    kind: 'docker-ssh',
    host: row.host,
    username: row.username,
    port: row.port,
    remoteBaseDir: row.remoteBaseDir,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

function cleanOptionalString(value: unknown, max = 512): string | undefined {
  if (typeof value !== 'string') return undefined;
  const trimmed = value.trim();
  if (trimmed === '') return undefined;
  return trimmed.length > max ? undefined : trimmed;
}

function cleanHost(value: unknown): string {
  if (typeof value !== 'string') {
    throw playbookError('invalid_input', 'host is required and must be a string');
  }
  const host = value.trim();
  if (host === '') {
    throw playbookError('invalid_input', 'host is required');
  }
  // A host is a DNS name / IP / user@host target — never whitespace or a
  // path-looking value. Keep validation strict but simple (no secrets).
  if (/[\s/\\]/.test(host)) {
    throw playbookError('invalid_input', 'host must be a bare host name or IP');
  }
  return host;
}

function cleanPort(value: unknown): number {
  if (value === undefined || value === null) return 22;
  const port = typeof value === 'number' ? value : Number(value);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw playbookError('invalid_input', 'port must be an integer between 1 and 65535');
  }
  return port;
}

const DOCKERFILE_TEMPLATE = (profileName: string): string => `# Partner container bundle — generated by the Ship playbook (package step)
# Profile: ${profileName}
# Build the bundle with build.sh on the build host, then:
#   docker build -t <app> . && docker run -p 4390:4390 <app>
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=4390
# core bundle + runtime deps + web static dist (build.sh prepares these)
COPY core-bundle.cjs /app/core-bundle.cjs
COPY node_modules /app/node_modules
COPY web /app/web
EXPOSE 4390
CMD ["node", "core-bundle.cjs"]
`;

const DOCKERIGNORE_TEMPLATE = `# Partner bundle context hygiene (generated)
.git
**/.git
*.log
.partner-trash
node_modules/.cache
`;

function buildShTemplate(projectDir: string): string {
  return `#!/bin/sh
# Generated by the Partner Ship playbook (package step). Run this on the
# BUILD HOST (node + npm available) AFTER the app itself was built
# (web/dist exists, core deps installed), BEFORE 'docker build .' in this
# folder. The core never bundles at runtime — this script is the deploy-time
# build the milestone documents (PLAN-M9 "package").
#
#   ./build.sh [PROJECT_DIR]     (defaults to the project captured below)
set -eu
PROJECT_DIR="\${1:-${projectDir}}"
OUT_DIR="\$(CDPATH= cd -- "\$(dirname "$0")" && pwd)"

if ! command -v npx >/dev/null 2>&1; then
  echo "build.sh: npx not found — run on a host with node + npm" >&2
  exit 1
fi

echo ">> bundling core (esbuild, single CJS; native deps stay external)"
npx --yes esbuild "\$PROJECT_DIR/core/src/index.ts" \\
  --bundle --platform=node --format=cjs \\
  --external:better-sqlite3 --external:@napi-rs/keyring \\
  --outfile="\$OUT_DIR/core-bundle.cjs"

echo ">> copying runtime node_modules"
mkdir -p "\$OUT_DIR/node_modules"
cp -R "\$PROJECT_DIR/node_modules/." "\$OUT_DIR/node_modules/"

if [ -d "\$PROJECT_DIR/web/dist" ]; then
  echo ">> copying web static dist"
  cp -R "\$PROJECT_DIR/web/dist" "\$OUT_DIR/web"
else
  echo ">> no web/dist found — container will serve without a bundled SPA"
fi

echo ">> bundle ready in \$OUT_DIR — docker build . next"
`;
}

const README_TEMPLATE = (profile: DeployProfileRow, files: string[]): string => `# Partner Ship bundle — ${profile.name}

Generated by the Ship playbook (package step) for deploy profile \`${profile.id}\`
(host \`${profile.host}:${profile.port}\`${profile.username !== null ? `, user \`${profile.username}\`` : ''}${
  profile.remoteBaseDir !== null ? `, base dir \`${profile.remoteBaseDir}\`` : ''
}).

## Layout

${files.map((file) => `- \`${file}\``).join('\n')}

## Build (on the build host)

1. Ensure the project has its dependencies installed and \`web/dist\` built.
2. Run \`./build.sh\` (optionally with the project dir as the first arg).
   It bundles the core with esbuild, copies runtime \`node_modules\` and the
   web static dist into this folder.
3. \`docker build -t <app> .\`
4. \`docker run -p 4390:4390 -e PORT=4390 <app>\` — the app listens on
   loopback INSIDE the container; put it behind your existing reverse proxy.

## Notes & environment gates

- Native modules (better-sqlite3, keyring) are copied from the build host —
  build on the same OS/arch as the target, or rebuild them in a multi-stage
  Dockerfile for \`node:20-alpine\` (musl).
- The core serves the API on \`PORT\` (default 4390); pairing/session
  security is unchanged.
- LIVE push/deploy to org infrastructure is environment-gated and NOT part
  of this milestone (PLAN-M9 "Out of scope"): this folder is the artifact
  the deploy step consumes once credentials/infra exist.
- No secrets are stored in or generated into this bundle. \`env_extra\`
  injection is reserved for a later milestone and never accepts secret
  values through the API.
`;

export function createDeployManager(options: DeployManagerOptions): DeployManager {
  const { store, audit } = options;
  const now = options.now ?? Date.now;

  function list(): DeployProfile[] {
    return store.list().map(rowToProfile);
  }

  function create(input: DeployProfileInput): DeployProfile {
    const body = (input ?? {}) as DeployProfileInput;
    const name = cleanOptionalString(body.name);
    if (name === undefined) {
      throw playbookError('invalid_input', 'name is required and must be a non-empty string');
    }
    // v1 supports exactly one target kind (PLAN-M9 "kind only docker-ssh");
    // the wire input has no kind field, so nothing to accept here.
    const host = cleanHost(body.host);
    const port = cleanPort(body.port);
    const username = cleanOptionalString(body.username);
    const remoteBaseDir = cleanOptionalString(body.remoteBaseDir);

    // Duplicate display names are confusing in a roots-style picker.
    const duplicate = store.list().some((row) => row.name === name);
    if (duplicate) {
      throw playbookError('conflict', `a deploy profile named "${name}" already exists`);
    }

    const at = now();
    const id = randomUUID();
    const row: DeployProfileRow = {
      id,
      name,
      kind: 'docker-ssh',
      host,
      username: username ?? null,
      port,
      remoteBaseDir: remoteBaseDir ?? null,
      envExtra: null,
      createdAt: at,
      updatedAt: at,
    };
    store.insert(row);
    audit.log('web', 'deploy-profile.create', id, {
      name,
      host,
      port,
      username: username ?? null,
    });
    return rowToProfile(row);
  }

  function remove(id: string): void {
    const row = store.findById(id);
    if (row === undefined) {
      throw playbookError('not_found', 'deploy profile not found');
    }
    store.remove(id);
    audit.log('web', 'deploy-profile.remove', id, { name: row.name });
  }

  function packageProfile(profileId: string, input: DeployPackageInput): PackageResult {
    const profile = store.findById(profileId);
    if (profile === undefined) {
      throw playbookError('not_found', 'deploy profile not found');
    }
    const projectDir = typeof input.projectDir === 'string' ? input.projectDir.trim() : '';
    const outDir = typeof input.outDir === 'string' ? input.outDir.trim() : '';
    if (projectDir === '' || !isAbsolute(projectDir)) {
      throw playbookError('invalid_input', 'projectDir must be an absolute path');
    }
    if (!existsSync(projectDir) || !statSync(projectDir).isDirectory()) {
      throw playbookError('invalid_input', 'projectDir must be an existing directory');
    }
    if (outDir === '' || !isAbsolute(outDir)) {
      throw playbookError('invalid_input', 'outDir must be an absolute path');
    }

    mkdirSync(outDir, { recursive: true });

    const dockerfilePath = join(outDir, 'Dockerfile');
    const dockerignorePath = join(outDir, '.dockerignore');
    const readmePath = join(outDir, 'README.md');
    const buildShPath = join(outDir, 'build.sh');

    const dockerfile = DOCKERFILE_TEMPLATE(profile.name);
    writeFileSync(dockerfilePath, dockerfile, 'utf8');
    writeFileSync(dockerignorePath, DOCKERIGNORE_TEMPLATE, 'utf8');
    const files = [dockerfilePath, dockerignorePath, buildShPath, readmePath];
    writeFileSync(buildShPath, buildShTemplate(projectDir), 'utf8');
    chmodSync(buildShPath, 0o755);
    writeFileSync(
      readmePath,
      README_TEMPLATE(profile, [dockerfilePath, dockerignorePath, buildShPath, readmePath]),
      'utf8',
    );

    audit.log('web', 'deploy-profile.package', profileId, {
      name: profile.name,
      outDir,
      files: files.length,
    });
    return { profileId, outDir, files, dockerfile };
  }

  return { list, create, remove, package: packageProfile };
}
